name: Release charm to other tracks and channels

on:
  workflow_dispatch:
    inputs:
      destination-channel:
        description: 'Destination Channel'
        required: true
      origin-channel:
        description: 'Origin Channel'
        required: true
      base-name:
        description: 'Base Name'
        required: true
        default: 'ubuntu'
      base-channel:
        description: 'Base Channel'
        required: true
        default: '20.04'
      base-architecture:
        description: 'Base Architecture'
        required: true
        default: amd64

jobs:
  promote-charm:
    name: Promote charm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release charm to channel
        uses: canonical/charming-actions/release-charm@handle-charmcraft-structured-status
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: ${{ github.event.inputs.destination-channel }}
          origin-channel: ${{ github.event.inputs.origin-channel }}
          base-name: ${{ github.event.inputs.base-name }}
          base-channel: ${{ github.event.inputs.base-channel }}
          base-architecture: ${{ github.event.inputs.base-architecture }}
