name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * MON'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: List
        run: ls -la
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.118.0
        with:
          configurationFile: renovate/renovate-config.js
          token: ${{ github.token }}
